require "prawn"
require "prawn/table"

class MemberStatementPdf
  def initialize(member)
    @member = member
    @chama = member.chama
  end

  def render
    pdf = Prawn::Document.new(page_size: "A4", margin: 40)

    add_header(pdf)
    add_member_details(pdf)
    add_summary(pdf)
    add_contributions_table(pdf)
    add_footer(pdf)

    pdf.render
  end

  private

  def add_header(pdf)
    pdf.text "Chama Agent", size: 10, color: "888888"
    pdf.text @chama.name, size: 24, style: :bold
    pdf.text "Member Statement", size: 14, color: "555555"
    pdf.move_down 20
    pdf.stroke_horizontal_rule
    pdf.move_down 20
  end

  def add_member_details(pdf)
    pdf.text "Member", size: 10, color: "888888"
    pdf.text @member.name, size: 18, style: :bold
    pdf.move_down 4
    pdf.text @member.phone, size: 11, color: "555555"
    pdf.text "Joined: #{@member.joined_at.strftime('%d %B %Y')}", size: 11, color: "555555"
    pdf.move_down 24
  end

  def add_summary(pdf)
    summary_data = [
      ["Contribution Amount",   "KES #{number_with_delimiter(@chama.contribution_amount.to_i)} / #{@chama.frequency}"],
      ["Total Paid",            "KES #{number_with_delimiter(@member.total_paid)}"],
      ["Expected to Date",      "KES #{number_with_delimiter(@member.expected_total)}"],
      ["Outstanding Balance",   status_line]
    ]

    pdf.table(summary_data, cell_style: { borders: [:bottom], border_color: "eeeeee", padding: [8, 4] }, column_widths: [200, 300]) do
      column(0).font_style = :bold
      column(0).text_color = "555555"
    end

    pdf.move_down 24
  end

  def status_line
    if @member.arrears.zero?
      "KES 0 — Up to date"
    else
      "KES #{number_with_delimiter(@member.arrears)} — #{@member.months_behind} month(s) behind"
    end
  end

  def add_contributions_table(pdf)
    pdf.text "Contribution History", size: 12, style: :bold
    pdf.move_down 8

    contributions = @member.contributions.where(status: "completed").order(paid_at: :desc)

    if contributions.empty?
      pdf.text "No contributions recorded yet.", color: "888888", style: :italic
      return
    end

    header = [["Date", "Amount (KES)", "M-PESA Receipt", "Status"]]
    rows = contributions.map do |c|
      [
        c.paid_at.strftime("%d %b %Y"),
        number_with_delimiter(c.amount.to_i),
        c.mpesa_receipt,
        c.status.capitalize
      ]
    end

    pdf.table(header + rows, header: true, cell_style: { padding: [6, 8], size: 10 }, column_widths: [90, 100, 200, 100]) do
      row(0).font_style = :bold
      row(0).background_color = "f5f5f5"
      row(0).text_color = "333333"
    end
  end

  def add_footer(pdf)
    pdf.move_down 30
    pdf.stroke_horizontal_rule
    pdf.move_down 8
    pdf.text "Generated by Chama Agent on #{Date.today.strftime('%d %B %Y')}", size: 9, color: "888888", align: :center
  end

  def number_with_delimiter(number)
    ActionController::Base.helpers.number_with_delimiter(number)
  end
end